Repository gbowne1/reactsocialnetwork, pull requests merged in 2023-07, with the labels that each got.

#270 updating the readme
  README.md
  client/package-lock.json
  package-lock.json
Labels: documentation, needs-review

#276 BUG: propTypes Issue
  client/src/components/Panel/Panel.jsx
  client/src/pages/Friends/Friends.jsx
Labels: bug, needs-review

#286 Fixes for linting
  .prettierignore
  .prettierrc
  client/.eslintignore
  client/.eslintrc
  client/package.json
  e2e/cypress/screenshots/events.cy.js/Event tests -- should create a new event succesfully (failed).png
  server/db.sqlite
Labels: enhancement, infrastructure, needs-testing, medium-complexity
