Repository gbowne1/reactsocialnetwork, pull requests merged in 2023-02, with the labels that each got.

#48 #44 bug solved
  CONTRIBUTORS.md
  src/App.js
Labels: bug, help wanted, good first issue

#70 issue #60 - Added MUI icons to SideNav component
  src/assets/SideNav.css
  src/components/SideNav.jsx
Labels: enhancement

#71 fixed contributors markdown file table; added a very important name to the list
  CONTRIBUTORS.md
Labels: documentation

#90 All components rendering
  src/App.js
  src/assets/Footer.css
  src/assets/Terms.css
Labels: bug, enhancement, css

#94 There are 2 Routers fix.
  src/App.js
Labels: bug

#100 Fixed theme change bug
  src/App.js
  src/assets/Dashboard.css
  src/assets/Friends.css
  src/assets/Post.css
  src/assets/Profile.css
  src/assets/Settings.css
  src/assets/UserProfile.css
  src/components/Dashboard.jsx
  src/components/Friends.jsx
  src/components/Profile.jsx
  src/components/TopNav.jsx
  src/components/UserProfile.jsx
Labels: bug

#108 Added icons and menu items to dropdown menu.
  src/components/TopNav.jsx
Labels: bug, enhancement
