Repository gbowne1/reactsocialnetwork, pull requests merged in 2023-06, with the labels that each got.

#236 Translating CONTRIBUTING.md into Hindi and Spanish
  docs/CONTRIBUTING.hindi.md
  docs/CONTRIBUTING.spanish.md
Labels: documentation

#233 [Bug]: Fix the Help component's CSS #230
  client/src/components/Panel/Panel.css
  client/src/pages/HelpCenter/HelpCenter.jsx
Labels: css

#239 feat: Create Profile Modal
  client/src/pages/Profile/Profile.css
  client/src/pages/Profile/Profile.jsx
Labels: enhancement, feature

#237 Update CONTRIBUTING.Telugu.md
  docs/CONTRIBUTING.Telugu.md
  docs/CONTRIBUTING.md
Labels: documentation

#240 Add contribution on Russian
  docs/CONTRIBUTING.russian.md
Labels: documentation

#241 Login panel css issue
  client/src/components/CookieModal/CookieModal.css
  client/src/components/CookieModal/CookieModal.jsx
  client/src/pages/Login/Login.css
Labels: bug, css, design

#242 Cookie accept not working
  client/src/components/CookieModal/CookieModal.jsx
  e2e/cypress/e2e/cookie-modal.cy.js
Labels: bug, needs-review, needs-testing, refactor

#243 Create reusable modal
  client/src/components/CookieModal/CookieModal.css
  client/src/components/CookieModal/CookieModal.jsx
  client/src/components/CustomModal/CustomModal.css
  client/src/components/CustomModal/CustomModal.jsx
  client/src/components/Panel/Panel.jsx
  docs/REUSABLE_COMPONENTS.md
  e2e/cypress/e2e/cookie-modal.cy.js
  e2e/cypress/e2e/login.cy.js
  images/CustomModal.png
Labels: enhancement, frontend, feature, refactor

#246 [Bugfix] ESlint Shared config bug with shared-config
  client/.eslintrc
Labels: bug

#255 Create CONTRIBUTING.Bangla.md
  docs/CONTRIBUTING.Bangla.md
Labels: documentation, enhancement

#258 Initial commit of AdminDashboard change
  client/src/App.js
  client/src/layouts/SideNav/SideNav.jsx
  client/src/pages/AdminDashboard/Admin.Dashboard.css
  client/src/pages/AdminDashboard/AdminDashboard.jsx
  server/db.sqlite
Labels: enhancement, css, frontend, design, high-priority, medium-priority, high-complexity, medium-complexity, feature

#262 Fix cypress config error and CreateEventModal has CSS import error.
  client/package.json
  client/src/pages/Events/CreateEventModal/CreateEventModal.jsx
  e2e/cypress.config.js
  e2e/cypress/e2e/events.cy.js
  e2e/package-lock.json
  e2e/package.json
Labels: bug, enhancement, testing, needs-review, refactor, tech-debt

#264 Update unit tests
  client/src/pages/Events/CreateEventModal/__test___/CreateEventModal-flow.test.js
  client/src/pages/Events/SingleEvent/__test__/SingleEvent-buttons.test.js
  client/src/pages/Events/SingleEvent/__test__/SingleEvent-initial-state.test.js
  client/src/pages/Events/__test__/Event-attendance-filter.test.js
  client/src/pages/Events/__test__/Event-initial-state.test.js
  client/src/pages/Login/__test__/Login-alert-message.test.js
  client/src/pages/Login/__test__/Login-flow.test.js
  client/src/utils/renderComponent.js
Labels: bug, enhancement, testing, needs-review, refactor, tech-debt

#267 Applying Minor bugfixes to some items
  client/.eslintrc
  client/src/components/CustomModal/CustomModal.css
  client/src/pages/Friends/Friends.jsx
  client/src/pages/Register/Register.jsx
  server/db.sqlite
Labels: bug, css, needs-review

#268 This commit adds the start of a draw.io RSN template.
  docs/ReactSocialNetwork.drawio
Labels: documentation, enhancement, help wanted, design, infrastructure, needs-review, needs-testing, refactor, tech-debt
