Repository gbowne1/reactsocialnetwork, pull requests merged in 2023-10, with the labels that each got.

#288 Change /src/index.js to .jsx and remove Strict Mode
  client/src/index.jsx
Labels: enhancement

#293 Updated the outdated packages in client and server #278
  client/package-lock.json
  client/package.json
  server/package-lock.json
  server/package.json
Labels: enhancement, help wanted, good first issue, high-priority, needs-review, medium-complexity, hacktoberfest, devops

#295 Configured dependabot to update packages #294
  .github/dependabot.yml
Labels: enhancement, help wanted, high-priority, needs-review, needs-testing, medium-complexity, feature, hacktoberfest, devops

#296 Fixed #282 and #281 - added beginning of the friendship-related backend.
  client/src/components/PostForm/PostForm.jsx
  client/src/pages/Profile/Profile.css
  client/src/pages/Profile/Profile.jsx
  e2e/cypress/e2e/posts.cy.js
  e2e/cypress/utils/utils.js
  server/app.js
  server/database.js
  server/routes/friend-requests/acceptFriendRequest.js
  server/routes/friend-requests/createFriendRequest.js
  server/routes/friend-requests/getFriendRequestsReceived.js
  server/routes/friend-requests/getFriendRequestsSent.js
  server/routes/friend-requests/getUserFriends.js
  server/routes/friend-requests/rejectFriendRequest.js
  server/routes/friend-requests/unfriend.js
  server/routes/posts/createPost.js
  server/routes/users/createUser.js
  server/routes/users/getUser.js
  server/routes/users/updateUser.js
Labels: enhancement, frontend, backend, design, high-priority, medium-priority, needs-review, needs-testing, high-complexity, medium-complexity, feature

#300 Database update
  client/src/layouts/TopNav/TopNav.jsx
  server/db.sqlite
Labels: bug, frontend, backend, refactor

#307 Update README.md
  README.md
Labels: documentation

#310 User profile UI
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/components/CustomTabPanel/CustomTabPanel.jsx
  client/src/components/Post/Post.css
  client/src/components/PostForm/PostForm.jsx
  client/src/pages/Profile/Profile.css
  client/src/pages/Profile/Profile.jsx
  client/src/pages/UserProfile/UserProfile.css
  client/src/pages/UserProfile/UserProfile.jsx
  client/src/utils/fetchUserData.js
  client/src/utils/getFromLocalStorage.js
  client/src/utils/renderComponent.js
  e2e/cypress/e2e/cookie-modal.cy.js
  server/db.sqlite
  server/package-lock.json
  server/package.json
  server/routes/index.js
Labels: enhancement, css, frontend, high-priority, medium-priority, needs-review, needs-testing, high-complexity, medium-complexity, feature, need-review

#314 Ignored path version in Dependabot
  .github/dependabot.yml
Labels: devops
