Repository gbowne1/reactsocialnetwork, pull requests merged in 2023-05, with the labels that each got.

#195 Bugfix: bugfix .eslintrc to fix ESLint so it does not error
  .eslintrc
Labels: bug

#198 [Bugfix] Fix outdated and deprecated babel-eslint parser
  .babelrc
  .eslintrc
  CONTRIBUTORS.md
  package-lock.json
  package.json
Labels: bug

#201 Updated eslint config to omit redundant errors
  .eslintrc
  package.json
  src/App.js
Labels: bug, enhancement, help wanted

#206 Removed some packages and installed them as dev dependencies
  package-lock.json
  package.json
Labels: enhancement

#209 Login component refactor
  docs/REUSABLE_COMPONENTS.md
  images/LoadingSpinner.png
  images/ThemeSwitch.png
  src/components/LoadingSpinner/LoadingSpinner.css
  src/components/LoadingSpinner/LoadingSpinner.jsx
  src/components/ThemeSwitch/ThemeSwitch.css
  src/components/ThemeSwitch/ThemeSwitch.jsx
  src/pages/Login/Login.css
  src/pages/Login/Login.jsx
Labels: enhancement

#208 [BUG] Bugfix PR: Fix duplicate script entry
  package.json
Labels: bug

#211 Prettify project code
  .babelrc
  .eslintrc
  README.md
  docs/CONTRIBUTORS.md
  e2e/cypress/support/commands.js
  e2e/cypress/support/e2e.js
  package-lock.json
  package.json
  src/components/LoadingSpinner/LoadingSpinner.css
  src/components/LoadingSpinner/LoadingSpinner.jsx
  src/components/ThemeSwitch/ThemeSwitch.css
  src/components/ThemeSwitch/ThemeSwitch.jsx
  src/layouts/SideNav/SideNav.jsx
  src/pages/AdminDashboard/Admin.Dashboard.css
  src/pages/Editor/Editor.css
  src/pages/Editor/Editor.jsx
  src/pages/Events/CreateEventModal/CreateEventModal.jsx
  src/pages/Events/SingleEvent/SingleEvent.jsx
  src/pages/Login/Login.css
  src/pages/Login/Login.jsx
Labels: enhancement

#213 Adding better README.md
  README.md
Labels: documentation, enhancement

#215 Eslint config fix
  client/.eslintrc
Labels: bug, enhancement
