Repository gbowne1/reactsocialnetwork, pull requests merged in 2023-04, with the labels that each got.

#156 Help center initial work
  package-lock.json
  src/App.css
  src/App.js
  src/assets/HelpCenter.css
  src/assets/SubjectDetails.css
  src/components/HelpCenter/HelpCenter.jsx
  src/components/HelpCenter/SubjectDetails.jsx
  src/data/json/helpCenterContentCategories.json
  src/layouts/Footer/Footer.css
  src/variables.css
Labels: enhancement

#164 Login tests
  package-lock.json
  package.json
  src/App.test.js
  src/pages/Login/Login.jsx
  src/pages/Login/__test__/Login.test.js
Labels: enhancement

#165 Made SingleEvent info-panel text wider.
  src/pages/Events/SingleEvent/SingleEvent.css
Labels: enhancement

#171 Worked On the issue : Add method to accept cookies #54
  src/App.js
  src/pages/Login/Login.css
  src/pages/Login/Login.jsx
Labels: enhancement, help wanted, good first issue

#168 Fixing some issues with UserProfile.jsx and Profile.jsx
  src/pages/Profile/Profile.jsx
  src/pages/UserProfile/UserProfile.css
  src/pages/UserProfile/UserProfile.jsx
Labels: bug, enhancement

#187 Update packages
  package-lock.json
  package.json
Labels: bug, help wanted, good first issue

#190 Create event tests
  package.json
  src/components/Panel/Panel.jsx
  src/pages/Events/CreateEventModal/CreateEventModal.jsx
  src/pages/Events/CreateEventModal/__test___/CreateEventModal-flow.test.js
  src/pages/Events/CreateEventModal/__test___/CreateEventModal-initial-state.test.js
  src/pages/Events/CreateEventModal/__test___/CreateEventModal-validation.test.js
  src/pages/Events/Events.jsx
  src/pages/Events/SingleEvent/SingleEvent.jsx
  src/pages/Events/SingleEvent/__test__/SingleEvent-buttons.test.js
  src/pages/Events/SingleEvent/__test__/SingleEvent-initial-state.test.js
  src/pages/Events/__test__/Event-attendance-filter.test.js
  src/pages/Events/__test__/Event-initial-state.test.js
  src/utils/checkImage.js
Labels: enhancement

#191 Adding a reusable Editor component
  package-lock.json
  src/pages/AdminDashboard/Admin.Dashboard.css
  src/pages/Editor/Editor.css
  src/pages/Editor/Editor.jsx
Labels: enhancement
