Repository gbowne1/reactsocialnetwork, pull requests merged in 2023-03, with the labels that each got.

#115 Create login/register component
  src/App.js
  src/components/CustomAlert.jsx
  src/components/Login.jsx
  src/components/TopNav.jsx
  src/utils.js
Labels: enhancement

#117 Add theme to login
  src/App.js
  src/components/Login.jsx
Labels: enhancement, css

#119 Replaced p elements with span elements.
  src/components/Login.jsx
Labels: bug

#126 Add notification widget
  src/components/NotificationBell.jsx
  src/components/TopNav.jsx
Labels: enhancement

#129 Add contributors to CONTRIBUTORS.md
  CONTRIBUTORS.md
  TODO.md
  package-lock.json
  package.json
Labels: documentation

#130 fixing VSCode extension recommendations
  .vscode/extensions.json
  .vscode/settings.json
Labels: bug

#131 Add close icon
  src/components/CloseButton.jsx
  src/components/Dashboard.jsx
  src/components/Friends.jsx
  src/components/Profile.jsx
  src/components/Settings.jsx
  src/components/UserProfile.jsx
Labels: enhancement

#134 Add initial events component
  src/App.js
  src/assets/Events.css
  src/assets/SingleEvent.css
  src/components/Events.jsx
  src/components/SingleEvent.jsx
  src/variables.css
Labels: enhancement

#139 Fixed theme reseting on reload
  .gitignore
  package-lock.json
  src/App.js
  src/components/Dashboard.jsx
  src/components/Events.jsx
  src/components/Footer.jsx
  src/components/Friends.jsx
  src/components/Login.jsx
  src/components/NavBar.jsx
  src/components/NotFound.jsx
  src/components/Post.jsx
  src/components/Profile.jsx
  src/components/Settings.jsx
  src/components/SideNav.jsx
  src/components/SingleEvent.jsx
  src/components/Theme.jsx
  src/components/TopNav.jsx
  src/components/UserProfile.jsx
  src/helpers/getFromLocalStorage.js
  src/helpers/saveToLocalStorage.js
Labels: bug

#142 Feedback modal
  src/App.js
  src/assets/Feedback.css
  src/components/Dashboard.jsx
  src/components/Events.jsx
  src/components/Feedback.jsx
  src/components/Friends.jsx
  src/components/NotFound.jsx
  src/components/Post.jsx
  src/components/Profile.jsx
  src/components/Settings.jsx
  src/components/SideNav.jsx
  src/components/SingleEvent.jsx
  src/components/TopNav.jsx
  src/components/UserProfile.jsx
Labels: enhancement, css

#143 Login page labels dark mode
  src/assets/Login.css
  src/components/Login.jsx
Labels: enhancement, css, a11y

#144 This commit adds minor changes to Friends.jsx
  src/components/Friends.jsx
Labels: bug, enhancement, help wanted, question, css

#145 Add panel to create events
  package.json
  src/assets/CreateEventModal.css
  src/assets/Events.css
  src/assets/SingleEvent.css
  src/components/CreateEventModal.jsx
  src/components/Events.jsx
  src/components/SingleEvent.jsx
  src/data/eventsData.js
  src/data/placeholderImageUrl.js
  src/helpers/checkImage.js
  src/helpers/formatDate.js
  src/helpers/isValidUrl.js
Labels: enhancement, css

#150 Create snackbar
  src/components/CreateEventModal.jsx
  src/components/CustomAlert.jsx
  src/components/CustomSnackbar.jsx
  src/components/Events.jsx
  src/components/Login.jsx
  src/components/SingleEvent.jsx
  src/components/TopNav.jsx
Labels: documentation, enhancement
